# CrazyLogin config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazyLogin/src/config.yml
version: X.Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazyLogin/src/plugin.yml
database:
# database saveTypes can be MYSQL, FLAT and CONFIG
  saveType: FLAT
# whether the database should be saved on shutdown
  saveOnShutdown: true
# FLAT Database options
  FLAT:
# path relativ to PluginFolder for the flat database.
    filePath: accounts.db
# MYSQL Database options
# additional information about MYSQL can be fould here http://dev.bukkit.org/server-mods/crazycore/pages/mys-ql/
  MYSQL:
    connection:
      host: localhost
      port: '3306'
      dbname: Crazy
      user: root
      password: ''
    tableName: CrazyLogin_accounts
# whether all data are loaded on startup and remain loaded when player isn't online. 
# this may reduce the plugins RAM usage
# This is a beta option. There may be bugs.
    cached: true
# if static is true playerdata will not be updated on player join, 
# this may cause sync problems in databases used by more than one server.
    static: false
    columns:
      name: name
      password: password
      ips: ips
      lastAction: lastAction
# CONFIG Database options
  CONFIG:
# path inside config.yml
    path: accounts
    columns:
      name: name
      password: password
      ips: ips
      lastAction: lastAction
# if true you have to create a password, if false having a password is optional
alwaysNeedPassword: true
# you have to login again after being inactive/offline for at least x seconds
# when using a new ip you are logged out automatically
autoLogout: 3600
# when enabled you are kicked when having an account and you did not login after x seconds (-1=disabled)
autoKick: -1
# when enabled you are banned for x seconds after being kicked for waiting to long to login (-1=disabled)
autoTempBan: -1
# when enabled you are kicked when not having an account after x seconds (-1=disabled)
autoKickUnregistered: -1
# when enabled you are kicked when failing login x times (-1=disabled)
autoKickLoginFailer: 3
# when enabled you are banned for x seconds for failing to login (-1=disabled)
autoTempBanLoginFailer: -1
# when enabled you are kicked when using a none whitelisted command (true/false)
autoKickCommandUsers: false
# when enabled you cannot execute a command without having registered (works with autoKickCommandUsers) (true/false)
blockGuestCommands: false
# when enabled you cannot chat without having registered (true/false)
blockGuestChat: false
# when enabled you cannot join without having registered (use with mysql databases) (true/false)
blockGuestJoin: false
# guest data are removed when leaving the server 
# this include all CrazyPlugins, playerfile (if enabled), +more (if commands are setup)
# after removing searching for the playersname in all files of that server will have 0 results. (Best Case)
removeGuestData: false
# when enabled ingame registrations are disabled (command and pluginChannel) (true/false)
disableRegistrations: false
# when disabled request login/register messages are spammed every cancelled action, when enabled only every 5 seconds (true/false)
doNotSpamRequests: false
# only ask the player once to create a password (if alwaysNeedPassword=false) (true/false)
doNotSpamRegisterRequests: false
# these commands can be executed as guest (even if blockGuestCommands is enabled) or when not logged in
commandWhitelist:
- /login .*
- /register .*
- /language [a-z][a-z]_[a-z][a-z]
- /language select.*
- /language list.*
- /worldedit cui
# the encryption alogrithm used to encrypt your passwords. http://dev.bukkit.org/server-mods/crazylogin/pages/encryption/
encryptor:
  name: CrazyCrypt1
# automatically delete accounts that haven't been used for x days(-1=disabled)
# WARNING: deletes all data belonging to this player (including those saved in other plugins; equals "/crazycore delete Player")
autoDelete: -1
# block player join with an online players name (prevents Logged in from another location messages) (true/false)
forceSingleSession: true
# bypass forceSingleSession when using the same ip (true/false)
forceSingleSessionSameIPBypass: true
# when enabled you are teleported to spawn until login
forceSaveLogin: false
# when enabled your inventory is wiped until login
hideInventory: false
# maximum players allowed to play on your server at once
maxOnlinesPerIP: 3
# maximum players allowed to register an account using the same ip on your server
maxRegistrationsPerIP: 3
# call special events (do not enable it, if you don't need it)
# send raw passwords to other plugins when changing passwords
pluginCommunicationEnabled: false
# you can move x blocks from the location you joined when not logged in
# when set to 0 you cannot move/rotate
moveRange: 5.0
# when enabled only default chars are allowed in a players name (true/false/[a-zA-Z0-9_]/...)
filterNames: false
# check a players name case for its char case (true/false)
# when enabled a player cannot join as "PLaYer" when he registered as "Player"
# some encryptions may fail when a player has different char cases.
# a player cannot bypass login by using an different name case.
# WARNING: very old datas of this plugin saved their data using lowercase names.
blockDifferentNameCases: false
# minimun length of player names
minNameLength: 3
# maximum length of player names (minecraft max is 16)
maxNameLength: 16
# additional information about logging can be found here http://dev.bukkit.org/server-mods/crazycore/pages/logging/
#logs:
#  Login:
#    path: false
#    console: false
#  ChatBlocked:
#    path: false
#    console: false
#  CommandBlocked:
#    path: false
#    console: false
#  Logout:
#    path: false
#    console: false
#  AccessDenied:
#    path: false
#    console: false
#  Quit:
#    path: false
#    console: false
#  Join:
#    path: false
#    console: false
#  LoginFail:
#    path: false
#    console: false
