# CrazyLogin config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazyLogin/src/config.yml
version: X.Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazyLogin/src/plugin.yml
# the chat header used ingame (this cannot be changed via any kind of reload)
chatHeader: '&C[&ACrazyLogin&C] &F'
database:
# database saveTypes can be MYSQL, FLAT and CONFIG
  saveType: FLAT
# whether the database should be saved on shutdown
  saveOnShutdown: true
# CONFIG Database options
  CONFIG:
# path inside config.yml
    path: accounts
    columns:
      name: name
      password: password
      ips: ips
      lastAction: lastAction
# FLAT Database options
  FLAT:
# path relativ to PluginFolder for the flat database.
    filePath: accounts.db
# MYSQL Database options
# additional information about MYSQL can be fould here http://dev.bukkit.org/server-mods/crazycore/pages/mys-ql/
  MYSQL:
    connection:
      host: localhost
      port: '3306'
      dbname: Crazy
      user: root
      password: ''
    tableName: CrazyLogin_accounts
# whether all data are loaded on startup and remain loaded when player isn't online. 
# this may reduce the plugins RAM usage
    cached: true
# if static is true playerdata will not be updated on player join, 
# this may cause sync problems in databases used on more than one server.
    static: false
    columns:
      name: name
      password: password
      ips: ips
      lastAction: lastAction
# SQLITE Database options
  SQLITE:
    connection:
      path: plugins/CrazyLogin/accounts.sqlite
    tableName: CrazyLogin_accounts
# whether all data are loaded on startup and remain loaded when player isn't online. 
# this may reduce the plugins RAM usage
    cached: true
# if static is true playerdata will not be updated on player join, 
# this may cause sync problems in databases used on more than one server.
    static: false
    columns:
      name: name
      password: password
      ips: ips
      lastAction: lastAction
# if true you have to create a password, if false having a password is optional
alwaysNeedPassword: true
# whether passwords have to be confirmed
# Ex: /register <Password> <Password>
confirmPassword: false
# if true if everyone is logged in protection will be disabled to decrease overall performance usage, 
# but increase join, login and quit performance 
dynamicProtection: false
# hides LOGIN.FAILEDWARN & COMMAND.EXPLOITWARN messages
# INFO: some other warn messages will be hidden in the future too.
# WARNING: you won't notice any (blocked) attempt to hack the server (until he managed to do so). 
hideWarnings: false
# you have to login again after being inactive/offline for at least x seconds
# when using a new ip you are logged out automatically
autoLogout: 3600
# when enabled you are kicked when having an account and you did not login after x seconds (-1=disabled)
autoKick: -1
# when enabled you are banned for x seconds after being kicked for waiting to long to login (-1=disabled)
autoTempBan: -1
# when enabled you are kicked when not having an account after x seconds (-1=disabled)
autoKickUnregistered: -1
# when enabled you are kicked when failing login x times (-1=disabled)
autoKickLoginFailer: 3
# when enabled you are banned for x seconds for failing to login (-1=disabled)
autoTempBanLoginFailer: -1
# when enabled you are kicked when using a none whitelisted command (true/false)
autoKickCommandUsers: false
# when enabled you cannot execute a command without having registered (works with autoKickCommandUsers) (true/false)
blockGuestCommands: true
# when enabled you cannot chat without having registered (true/false)
blockGuestChat: false
# when enabled you cannot join without having registered (use with mysql databases) (true/false)
blockGuestJoin: false
# guest data are removed when leaving the server 
# this include all CrazyPlugins, playerfile (if enabled), +more (if commands are setup)
# after removing searching for the playersname in all files of that server will have 0 results. (Best Case)
removeGuestData: false
# if set to true ingame registrations are disabled (command and pluginChannel) (true/false)
disableRegistrations: false
# if set to true you cannot use adminlogin command (true/false)
disableAdminLogin: false
# if set to true you cannot use tokenlogin command (true/false)
disableTokenLogin: false
# when disabled request login/register messages are spammed every cancelled action, when enabled only every 5 or more seconds (true/false)
doNotSpamAuthRequests: false
# only ask the player once to create a password (if alwaysNeedPassword=false) (true/false)
doNotSpamRegisterRequests: false
# these commands can be executed as guest (even if blockGuestCommands is enabled) or when not logged in
commandWhitelist:
- /l[ogin]?(\z| .*)
- /register(\z| .*)
- /language(\z| [a-z]{2,3}_[a-z]{2,3})
- /language select(\z| .*)
- /language list(\z| .*)
- /worldedit cui
# the encryption alogrithm used to encrypt your passwords. http://dev.bukkit.org/server-mods/crazylogin/pages/encryption/
encryptor:
  name: CrazyCrypt1
# automatically delete accounts that haven't been used for x days(-1=disabled)
# WARNING: deletes all data belonging to this player (including those saved in other plugins; equals "/crazycore player delete <Player>")
autoDelete: -1
# block player join with an online players name (prevents Logged in from another location messages) (true/false)
forceSingleSession: true
# bypass forceSingleSession when using the same ip (true/false)
forceSingleSessionSameIPBypass: true
# activates the preLoginSecurity x ticks later (hideInventory / forceSaveLogin) (false/0, 1 , ...)
# this is intended to allow customSpawns and joinRewards
delayPreRegisterSecurity: 5
# activates the preLoginSecurity x ticks later (hideInventory / forceSaveLogin) (false/0, 1 , ...)
# this is intended to allow customSpawns and joinRewards
# WARNING: some hacked clients may be able to use that time to read the inventory/location
delayPreLoginSecurity: false
# when enabled you are teleported to spawn until login (true/false)
# this fixes issues with AntiCheatPlugins whilte not logged in an being in mid air.
forceSaveLogin: false
# custom saveLogin locations for each world
saveLoginLocations: {}
##  world:
##    x: 1500
##    y: -300
##    z: 0.1
### this parameters are optional
##    world: world
##    yaw: 0
##    pitch: 0
# when enabled your inventory is hidden until login. (true/false)
hideInventory: false
# hide every player which isn't logged in. (true/false)
hidePlayer: false
# hide chat from players who aren't logged in to avoid espionage. (true/false)
hideChat: false
# Delay Join messages until login / hide Quit messages if not logged in. (true/false)
delayJoinQuitMessages: false
# use the multilingual messages defined in the lang files. (true/false)
useCustomJoinQuitMessages: true
# hide Password from Console (Player issues command: /login Password) (true/false)
# INFO: This could bypass some command protections/mechanics from other plugins in very rare cases.
hidePasswordsFromConsole: false
# maximum players allowed to play on your server at once
maxOnlinesPerIP: 3
# maximum players allowed to register an account using the same ip on your server
maxRegistrationsPerIP: 3
# call special events (do not enable it, if you don't need it)
# send raw passwords to other plugins when changing passwords
pluginCommunicationEnabled: false
# you can move x blocks from the location you joined when not logged in
# when set to 0 you cannot move/rotate
moveRange: 5.0
# when enabled only default chars are allowed in a players name (true/false/[a-zA-Z0-9_]/...)
filterNames: true
# check a players name case for its char case (true/false)
# when enabled a player cannot join as "PLaYer" when he registered as "Player"
# some encryptions may fail when a player has different char cases.
# INFO: a player cannot bypass login by using an different name case at any time.
blockDifferentNameCases: false
# minimun length of player names
minNameLength: 3
# maximum length of player names (minecraft max is 16)
maxNameLength: 16
# additional information about logging can be found here http://dev.bukkit.org/server-mods/crazycore/pages/logging/
##logs:
##  Join:
##    path: false
##    console: false
##  Quit:
##    path: false
##    console: false
##  Login:
##    path: false
##    console: false
##  Account:
##    path: false
##    console: false
##  Logout:
##    path: false
##    console: false
##  LoginFail:
##    path: false
##    console: false
##  ChatBlocked:
##    path: false
##    console: false
##  CommandBlocked:
##    path: false
##    console: false
##  AccessDenied:
##    path: false
##    console: false
